language: elixir
elixir:
  - 1.7.3
  - 1.8.2
otp_release:
  - 20.0
  - 21.0
env:
  - MIX_ENV=test
before_script:
  - mix local.hex --force && mix deps.get
script:
  - mix test
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
